using System.Globalization;

namespace AthanDesktop;

/// <summary>
/// The interface in English and Arabic.
///
/// WPF has no equivalent of Android's values-ar, so the two languages live in
/// one table here. It is GENERATED from the Android app's string resources by
/// tools/gen-strings.py - the phone is the source of truth for wording, and
/// hand-copying 90 strings between two repositories would guarantee they drift.
/// Edit the Android resources and re-run the script; do not edit this file.
///
/// Like the phone, Arabic uses Western digits: the forms in everyday use, and
/// on every other clock the reader looks at, are the Western ones.
/// </summary>
public static class Strings
{
    private static readonly Dictionary<string, (string En, string Ar)> Table = new()
    {
        ["fajr"] = ("Fajr", "الفجر"),
        ["sunrise"] = ("☀️ Sunrise", "☀️ الشروق"),
        ["dhuhr"] = ("Dhuhr", "الظهر"),
        ["asr"] = ("Asr", "العصر"),
        ["maghrib"] = ("Maghrib", "المغرب"),
        ["isha"] = ("Isha", "العشاء"),
        ["set_location"] = ("Set location", "تعيين الموقع"),
        ["location_set"] = ("Location set", "تم تعيين الموقع"),
        ["settings"] = ("Settings", "الإعدادات"),
        ["qibla"] = ("Qibla", "القبلة"),
        ["close"] = ("Close", "إغلاق"),
        ["stop"] = ("Stop", "إيقاف"),
        ["next_in"] = ("{0} in {1}", "{0} بعد {1}"),
        ["countdown_hm"] = ("{0}h {1:00}m", "{0} س {1:00} د"),
        ["countdown_ms"] = ("{0}m {1:00}s", "{0} د {1:00} ث"),
        ["mode_sound"] = ("Sound", "صوت"),
        ["mode_silent"] = ("Silent", "صامت"),
        ["calculation_method"] = ("Calculation method", "طريقة الحساب"),
        ["juristic_method"] = ("Asr method", "حساب العصر"),
        ["time_adjustment"] = ("Time adjustment", "تعديل الوقت"),
        ["madhab_shafi"] = ("Standard", "الجمهور"),
        ["madhab_hanafi"] = ("Hanafi", "الحنفي"),
        ["adjust_none"] = ("No adjustment", "بدون تعديل"),
        ["fajr_athan_sound"] = ("Fajr Athan Sound", "صوت أذان الفجر"),
        ["athan_sound_other"] = ("Athan Sound (other prayers)", "صوت الأذان (باقي الصلوات)"),
        ["app_volume"] = ("App Volume", "مستوى صوت التطبيق"),
        ["credits_row"] = ("Resources & credits", "المصادر والشكر"),
        ["credits_title"] = ("Resources & credits", "المصادر والشكر"),
        ["credits_intro"] = ("Where every athan included in this app came from. Most were published by IslamWeb (islamweb.net), which permits its material to be used for non-commercial purposes as long as the source is named. This app is free, carries no ads, and sells nothing.", "مصدر كل أذان مضمَّن في هذا التطبيق. معظمها منشور على «إسلام ويب» (islamweb.net)، وهو يجيز استخدام مواده لأغراض غير تجارية ما دام المصدر مذكورًا. هذا التطبيق مجاني، ولا يحمل إعلانات، ولا يبيع شيئًا."),
        ["credits_islamweb_permission"] = ("IslamWeb permission — fatwa no. 379009", "إذن إسلام ويب — فتوى رقم 379009"),
        ["credit_source"] = ("Source: {0}", "المصدر: {0}"),
        ["credit_source_unknown"] = ("Source: islamweb.net (reciter not named in the recording)", "المصدر: islamweb.net (اسم المؤذن غير مذكور في التسجيل)"),
        ["credit_own_recording"] = ("Recorded by the developer", "تسجيل من إعداد المطوّر"),
        ["credits_software"] = ("Software", "البرمجيات"),
        ["credits_weather"] = ("Weather", "الطقس"),
        ["credits_weather_detail"] = ("Temperature data by Open-Meteo.com, used under CC BY 4.0. Requested only while the temperature is switched on.", "بيانات درجة الحرارة من Open-Meteo.com، مستخدمة بموجب رخصة CC BY 4.0. ولا تُطلب إلا عند تفعيل درجة الحرارة."),
        ["about"] = ("About", "عن التطبيق"),
        ["about_contact"] = ("Contact", "للتواصل"),
        ["about_privacy"] = ("No data is collected from this app. The one thing it ever sends is your coordinates, to look up the temperature — and only while that is switched on. Turn it off in Settings and the app makes no network requests at all.", "لا يجمع هذا التطبيق أي بيانات. والشيء الوحيد الذي يُرسله هو إحداثياتك لمعرفة درجة الحرارة — وذلك فقط عند تفعيلها. وإن أوقفتها من الإعدادات لم يعد يتصل بالشبكة إطلاقًا."),
        ["adhkar_morning"] = ("Morning Athkar", "أذكار الصباح"),
        ["adhkar_evening"] = ("Evening Athkar", "أذكار المساء"),
        ["adhkar_morning_when"] = ("Said after Fajr, until sunrise", "تُقال بعد صلاة الفجر إلى طلوع الشمس"),
        ["adhkar_evening_when"] = ("Said after Asr, until sunset", "تُقال بعد صلاة العصر إلى غروب الشمس"),
        ["adhkar_unavailable"] = ("Couldn't load the athkar", "تعذّر تحميل الأذكار"),
        ["temperature"] = ("Temperature", "درجة الحرارة"),
        ["temperature_enable"] = ("Show the temperature", "إظهار درجة الحرارة"),
        ["temperature_explainer"] = ("The only part of Athan that uses the internet. Your coordinates are sent to Open-Meteo to look up the weather where you are — nothing else is sent, and nothing is stored. Turn this off and the app makes no network requests at all.", "الجزء الوحيد من التطبيق الذي يستخدم الإنترنت. تُرسل إحداثياتك إلى Open-Meteo لمعرفة الطقس عندك — ولا يُرسل شيء سواها، ولا يُحفظ شيء. وإذا أوقفته لم يعد التطبيق يتصل بالشبكة إطلاقًا."),
        ["temperature_units"] = ("Units", "الوحدة"),
        ["unit_celsius"] = ("Celsius", "مئوية"),
        ["unit_fahrenheit"] = ("Fahrenheit", "فهرنهايت"),
        ["temperature_summary_on"] = ("On · {0}", "مفعّل · {0}"),
        ["temperature_summary_off"] = ("Off · no network requests", "متوقف · بلا اتصال بالشبكة"),
        ["temperature_notice_title"] = ("Show the temperature?", "هل تريد إظهار درجة الحرارة؟"),
        ["temperature_notice_body"] = ("Athan can show the current temperature where you are. To do it, your coordinates are sent to Open-Meteo — that is the one and only thing this app ever sends anywhere.\n\nEverything else — prayer times, the qibla, the athkar, the Ramadan calendar — is calculated on this phone and works with no connection at all.\n\nYou can change this any time in Settings.", "يمكن للتطبيق عرض درجة الحرارة عند موقعك. ولذلك تُرسل إحداثياتك إلى Open-Meteo — وهذا هو الشيء الوحيد الذي يُرسله هذا التطبيق إلى أي جهة.\n\nأمّا كل ما عدا ذلك — مواقيت الصلاة، والقبلة، والأذكار، وتقويم رمضان — فيُحسب على هذا الهاتف ويعمل دون أي اتصال.\n\nويمكنك تغيير ذلك متى شئت من الإعدادات."),
        ["temperature_notice_yes"] = ("Show it", "أظهرها"),
        ["temperature_notice_no"] = ("No, stay offline", "لا، ابقَ دون اتصال"),
        ["ramadan"] = ("Ramadan calendar", "تقويم رمضان"),
        ["ramadan_short"] = ("Ramadan Cal", "تقويم رمضان"),
        ["ramadan_title"] = ("Ramadan {0} AH", "رمضان {0} هـ"),
        ["ramadan_col_day"] = ("#", "#"),
        ["ramadan_col_date"] = ("Date", "التاريخ"),
        ["ramadan_col_suhoor"] = ("Suhoor", "السحور"),
        ["ramadan_col_iftar"] = ("Iftar", "الإفطار"),
        ["ramadan_footnote"] = ("Dates follow the Umm al-Qura calendar, which is calculated rather than sighted, so your local mosque may begin or end the month a day either side. Check these times against your mosque's timetable before relying on them.", "التواريخ وفق تقويم أم القرى، وهو محسوب لا مبنيّ على الرؤية، فقد يبدأ مسجدك الشهر أو يختمه قبل ذلك بيوم أو بعده. فراجع هذه المواقيت مع جدول مسجدك قبل الاعتماد عليها."),
        ["ramadan_no_location"] = ("Set your location to build the timetable", "عيّن موقعك لإنشاء الجدول"),
        ["ramadan_prompt_title"] = ("Ramadan is coming", "رمضان على الأبواب"),
        ["ramadan_prompt_body"] = ("Would you like the whole month's timetable — suhoor, iftar and every prayer, for all {0} days?", "هل تريد جدول الشهر كاملاً — السحور والإفطار وكل الصلوات، لـ {0} يومًا؟"),
        ["ramadan_prompt_yes"] = ("Show me", "أرِني"),
        ["ramadan_prompt_no"] = ("Not this year", "ليس هذا العام"),
        ["ramadan_auto_offer"] = ("Offer this automatically each Ramadan", "اعرضه تلقائيًا كل رمضان"),
        ["after_athan_dua"] = ("Play the du'aa after the athan", "تشغيل الدعاء بعد الأذان"),
        ["after_athan_dua_explainer"] = ("دعاء بعد الأذان — starts a couple of seconds after the call ends. The athan and the du'aa count as one announcement, so the window stays until both are done.", "يبدأ بعد انتهاء الأذان بثوانٍ. والأذان والدعاء إعلان واحد، فتبقى النافذة حتى ينتهيا معًا."),
        ["reminder_title_short"] = ("Prayer time heads-up", "تنبيه قبل الصلاة"),
        ["reminder_summary_off"] = ("Off", "متوقف"),
        ["reminder_explainer"] = ("A short pop-up before each prayer, so you can be ready in time.", "نافذة قصيرة تظهر قبل كل صلاة، لتكون مستعدًا في وقتك."),
        ["time_adjustment_hint"] = ("Shifts every prayer time. Use this when the clock changes seasonally or the local timetable differs from the calculation.", "يُزيح كل أوقات الصلاة. استخدمه عند تغيّر التوقيت موسميًا، أو عندما يختلف تقويم بلدك عن الحساب."),
        ["madhab_shafi_long"] = ("Standard (Shafi'i, Maliki, Hanbali)", "الجمهور (الشافعي والمالكي والحنبلي)"),
        ["for_fajr"] = ("Fajr", "الفجر"),
        ["for_other_prayers"] = ("Dhuhr, Asr, Maghrib, Isha", "الظهر والعصر والمغرب والعشاء"),
        ["about_version"] = ("Version {0}", "الإصدار {0}"),
        ["about_developed_by"] = ("Developed by Ahmed Khalaf (A.K.)", "تطوير A.M.K.&#x200E;"),
        ["about_github"] = ("Follow me on GitHub: github.com/nandxorandor", "تابعني على GitHub: github.com/nandxorandor"),
        ["about_privacy"] = ("No data is collected from this app. The one thing it ever sends is your coordinates, to look up the temperature — and only while that is switched on. Turn it off in Settings and the app makes no network requests at all.", "لا يجمع هذا التطبيق أي بيانات. والشيء الوحيد الذي يُرسله هو إحداثياتك لمعرفة درجة الحرارة — وذلك فقط عند تفعيلها. وإن أوقفتها من الإعدادات لم يعد يتصل بالشبكة إطلاقًا."),
        ["about_audio_credit"] = ("Athan recordings", "تسجيلات الأذان"),
        ["about_audio_credit_detail"] = ("Two of the bundled athans are my own recordings; the rest were published by IslamWeb and are included with the source named — see Settings → Resources & credits. You can use any recording you prefer instead: Settings → Athan audio options.", "اثنان من الأذانات المضمّنة من تسجيلي الخاص، وبقيتها منشورة على «إسلام ويب» ومضمَّنة مع ذكر المصدر — انظر الإعدادات ← المصادر والشكر. ويمكنك استخدام أي تسجيل تفضّله بدلًا منها: الإعدادات ← خيارات صوت الأذان."),
        ["credits_software_detail"] = ("Prayer times are calculated with the open-source “adhan” library by Batoul Apps. Everything the app shows — prayer times, the qibla, the athkar and the Ramadan calendar — is computed on your phone. The temperature is the only exception, and it can be switched off.", "تُحسب أوقات الصلاة بمكتبة «adhan» مفتوحة المصدر من Batoul Apps. وكل ما يعرضه التطبيق — مواقيت الصلاة والقبلة والأذكار وتقويم رمضان — يُحسب على هاتفك. ودرجة الحرارة هي الاستثناء الوحيد، ويمكن إيقافها."),
        ["athan_audio_options"] = ("Athan audio options", "خيارات صوت الأذان"),
        ["dont_show_again"] = ("Don't show this again", "لا تعرض هذا مرة أخرى"),
        ["open_settings"] = ("Open settings", "فتح الإعدادات"),
        ["search"] = ("Search", "بحث"),
        ["use_gps"] = ("Use GPS", "تحديد موقعي"),
        ["city_hint"] = ("City name", "اسم المدينة"),
        ["city_not_found"] = ("Couldn't find that city", "تعذّر العثور على هذه المدينة"),
        ["delete"] = ("Delete", "حذف"),
        ["not_now"] = ("Not now", "ليس الآن"),
        ["view_downloaded_short"] = ("View", "عرض"),
        ["lang_english"] = ("English", "English"),
        ["lang_arabic"] = ("عربي", "عربي"),
        ["language"] = ("Language", "اللغة"),
        ["method_north_america"] = ("North America (ISNA)", "أمريكا الشمالية (ISNA)"),
        ["method_mwl"] = ("Muslim World League", "رابطة العالم الإسلامي"),
        ["method_egyptian"] = ("Egyptian General Authority", "الهيئة المصرية العامة للمساحة"),
        ["method_karachi"] = ("Karachi", "كراتشي"),
        ["method_umm_al_qura"] = ("Umm al-Qura (Makkah)", "أم القرى (مكة المكرمة)"),
        ["method_dubai"] = ("Dubai", "دبي"),
        ["method_moonsighting"] = ("Moonsighting Committee", "لجنة رؤية الهلال"),
        ["method_kuwait"] = ("Kuwait", "الكويت"),
        ["method_qatar"] = ("Qatar", "قطر"),
        ["method_singapore"] = ("Singapore", "سنغافورة"),
        ["method_turkey"] = ("Turkey", "تركيا"),
        ["method_tehran"] = ("Tehran", "طهران"),
        ["method_other"] = ("Other", "أخرى"),
        ["category_developer"] = ("Developer athan", "أذان المطوّر"),
        ["category_mecca"] = ("Mecca — Masjid al-Haram", "مكة — المسجد الحرام"),
        ["category_madina"] = ("Madina — Masjid an-Nabawi", "المدينة — المسجد النبوي"),
        ["category_emarat"] = ("Emirates", "الإمارات"),
        ["category_various"] = ("Various reciters", "مؤذنون متنوعون"),
        ["category_egyptian"] = ("Egyptian", "مصر"),
        ["category_turkish"] = ("Turkish", "تركيا"),
        ["category_kuwait"] = ("Kuwait", "الكويت"),
        ["category_georgia"] = ("Georgia", "جورجيا"),
        ["category_fajr"] = ("Fajr athan", "أذان الفجر"),
        ["mode_popup"] = ("Popup", "نافذة"),
        ["test_athan"] = ("Test athan", "تجربة الأذان"),
        ["next_prayer"] = ("NEXT PRAYER", "الصلاة القادمة"),
        ["start_with_windows"] = ("Start Athan when I sign in", "تشغيل التطبيق عند بدء الويندوز"),
        ["show_window_on_startup"] = ("Show the Athan window when it starts", "إظهار النافذة عند البدء"),
        ["athkar_button"] = ("Athkar", "الأذكار"),
        ["credits_short"] = ("Credits", "المصادر"),
        ["at_time"] = ("at {0}", "الساعة {0}"),
        ["qibla_line"] = ("Qibla {0}° from true north  ·  {1} km to Mecca", "القبلة {0}° من الشمال الجغرافي  ·  {1} كم إلى مكة"),
        ["no_location_yet"] = ("No location yet", "لم يُحدّد الموقع بعد"),
        ["sec_athan_sound"] = ("ATHAN SOUND", "صوت الأذان"),
        ["sec_before_prayer"] = ("BEFORE THE PRAYER", "قبل الصلاة"),
        ["sec_calculation"] = ("CALCULATION", "الحساب"),
        ["sec_windows"] = ("WINDOWS", "ويندوز"),
        ["sec_temperature"] = ("TEMPERATURE", "درجة الحرارة"),
        ["sec_ramadan"] = ("RAMADAN", "رمضان"),
        ["sec_about"] = ("ABOUT", "عن التطبيق"),
        ["sec_software"] = ("SOFTWARE", "البرمجيات"),
        ["sec_weather"] = ("WEATHER", "الطقس"),
        ["other_prayers"] = ("Other prayers", "باقي الصلوات"),
        ["reminder_enable_win"] = ("Show a heads-up before each prayer", "إظهار تنبيه قبل كل صلاة"),
        ["reminder_preview"] = ("Show me what it looks like", "أرِني كيف يبدو"),
        ["reminder_explainer_win"] = ("A silent popup so you can finish what you are doing. It closes itself after ten seconds.", "نافذة صامتة تتيح لك إنهاء ما بيدك، وتغلق نفسها بعد عشر ثوانٍ."),
        ["startup_explainer"] = ("Athan sits in the notification area, so prayers are called without you opening it. It keeps running there when you close the main window.", "يبقى التطبيق في شريط الإشعارات، فتُرفع الصلوات دون أن تفتحه. ويظل يعمل هناك بعد إغلاق النافذة الرئيسية."),
        ["show_window_explainer"] = ("Untick to have Athan start quietly in the notification area, with no window on your desktop.", "أزل التحديد ليبدأ التطبيق بهدوء في شريط الإشعارات دون نافذة على سطح المكتب."),
        ["ramadan_open"] = ("Ramadan calendar…", "تقويم رمضان…"),
        ["ramadan_auto_explainer"] = ("Asks once, in the fortnight before the first fast, whether you want the month's timetable. Dismissing it only silences that year.", "يسأل مرة واحدة في الأسبوعين السابقين لأول صوم إن كنت تريد جدول الشهر. وتجاهله يُسكته لذلك العام فقط."),
        ["about_athan"] = ("About Athan", "عن التطبيق"),
        ["method_label"] = ("Method", "الطريقة"),
    };

    /// <summary>The chosen language, following Windows until the user picks one.</summary>
    public static bool IsArabic =>
        App.Settings.Language.Length > 0
            ? App.Settings.Language == "ar"
            : CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "ar";

    public static string Get(string key) =>
        Table.TryGetValue(key, out var pair) ? (IsArabic ? pair.Ar : pair.En) : key;

    public static string Get(string key, params object[] args) =>
        string.Format(CultureInfo.InvariantCulture, Get(key), args);

    /// <summary>Arabic mirrors the whole window.</summary>
    public static System.Windows.FlowDirection Flow =>
        IsArabic ? System.Windows.FlowDirection.RightToLeft : System.Windows.FlowDirection.LeftToRight;
}
